### ISSUE TITLE
Icons are bugging

### ISSUE THREAD

**Issue by Tux0n0** [theonlyrealquality/Sauerbraten#1]
The client is difficult to install, i had to change the saubraten.exe files in the bin-folder xO

**Comment by Tux0n0** [comment]
and the background is bugging too

**Comment by theonlyrealquality** [comment]
You're right, I forgot to upload the right batch file.
And what's that with the bugging textures?

**Comment by Tux0n0** [comment]
"the bugging backgroundtexture" was a fail of the normal client
you should take the .exe programms to the bin folders
for example: rename Sauerbraten32.exe -> Sauerbraten.exe and move it to the bin folder
rename Sauerbraten64.exe -> Sauerbraten.exe and move it to the bin64 folder

**Comment by Tux0n0** [comment]
and i could help a little bit with seeking skins and scripting a little bit in cubescript ^^

**Comment by Tux0n0** [comment]
and "the bugging icons" were a fail of the normal client too

**Comment by theonlyrealquality** [comment]
Help is appreciated of course ;) mail me at theonlyrealquality@gmail.com
The executable are intended to be like that, if I renamed both to just sauerbraten.exe you wouldn't know which one has been downloaded. The batch file has been updated, so this problem should be fixed :)
