### ISSUE TITLE
Not saved settings

### ISSUE THREAD

**Issue by Tux0n0** [theonlyrealquality/Sauerbraten#2]
The client doesn't save the changed settings, the name and the resolution.
Can you fix it pls, so that it save everything?

**Comment by theonlyrealquality** [comment]
That was probably, because of one commit. I accidentally uploaded my config.cfg file too, which I removed now, so it has been deleted there. Please try again, if it's really broken :)
Settings are saved to `home/saved/config.cfg`

**Comment by Tux0n0** [comment]
I know why it can't save the settings, its trying to save them in the main-dir. and not in the mygames-dir., it can't save it in the main-dir. because i have as user no admin, and the game too.

**Comment by theonlyrealquality** [comment]
Try to install this client on a Stick or in a folder where you don't need admin.  
Or try to rewrite one line of sauerbraten.bat:
`start bin%SAUER_ARCH%\sauerbraten%SAUER_ARCH%.exe "-qhome" -glog.txt %* `
to:
`start bin%SAUER_ARCH%\sauerbraten%SAUER_ARCH%.exe -khome "-q$HOME\My Games\Sauerbraten" -glog.txt %*`
